server:
  port: 1221

logging:
  level:
    root: info

spring:
  batch:
    job:
      enabled: false
  cloud:
    config:
      enabled: false
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    url: jdbc:h2:~/batch-db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa